import { defineConfig } from 'vitepress'
import dynamicSidebar from './sidebar'
import dynamicSidebarEn from './sidebar-en'

// Build complete zh sidebar by merging static entries with dynamic ones.
// Dynamic entries come from sidebar.ts (auto-generated by scripts/generate_docs_index.py).
const zhSidebar = Object.assign(
  {
    '/zh/eu_mdr/': [
      { text: 'EU MDR 概述', link: '/zh/eu_mdr/' },
      { text: '认证时限', link: '/zh/eu_mdr/certification-timeline' },
      {
        text: '技术文件 (BPG Rev.4)', link: '/zh/eu_mdr/td/',
        collapsed: true,
        items: [
          { text: '器械描述与规格', link: '/zh/eu_mdr/td/device-description' },
          { text: '制造商提供的信息', link: '/zh/eu_mdr/td/information-supplied' },
          { text: '设计与制造', link: '/zh/eu_mdr/td/design-manufacturing' },
          { text: 'GSPR 检查表', link: '/zh/eu_mdr/td/gspr' },
          { text: '风险管理', link: '/zh/eu_mdr/td/risk-management' },
          {
            text: '验证与确认 (V&V)', link: '/zh/eu_mdr/td/verification-validation',
            collapsed: true,
            items: [
              { text: 'V&V 总览', link: '/zh/eu_mdr/td/vv/' },
              { text: '设计验证与确认', link: '/zh/eu_mdr/td/vv/design-vv' },
              { text: '生物相容性评价', link: '/zh/eu_mdr/td/vv/biocompatibility' },
              { text: '电气安全与EMC', link: '/zh/eu_mdr/td/vv/electrical-safety-emc' },
              { text: '软件V&V (IEC 62304)', link: '/zh/eu_mdr/td/vv/software-vv' },
              { text: '网络安全', link: '/zh/eu_mdr/td/vv/cybersecurity' },
              { text: '稳定性与货架期', link: '/zh/eu_mdr/td/vv/stability-shelf-life' },
              { text: '包装验证', link: '/zh/eu_mdr/td/vv/packaging' },
              { text: '灭菌验证', link: '/zh/eu_mdr/td/vv/sterilization' },
              { text: '可用性/人因工程', link: '/zh/eu_mdr/td/vv/usability' },
              { text: 'FDA 人因摘要 (2026)', link: '/zh/eu_mdr/td/vv/usability-fda-hf' },
              { text: '器械使用寿命', link: '/zh/eu_mdr/td/vv/device-lifetime' },
              { text: '测量/诊断功能', link: '/zh/eu_mdr/td/vv/measuring-diagnostic' },
              { text: 'MRI安全性', link: '/zh/eu_mdr/td/vv/mri-safety' },
              { text: '互联互操作性', link: '/zh/eu_mdr/td/vv/interoperability' },
              { text: '再处理验证', link: '/zh/eu_mdr/td/vv/reprocessing' },
              { text: '药械组合', link: '/zh/eu_mdr/td/vv/drug-device' },
              { text: '动物源组织', link: '/zh/eu_mdr/td/vv/animal-tissue' },
              { text: '人体源组织', link: '/zh/eu_mdr/td/vv/human-tissue' },
              { text: '吸收/扩散物质', link: '/zh/eu_mdr/td/vv/absorbed-substances' },
              { text: 'CMR/内分泌干扰', link: '/zh/eu_mdr/td/vv/cmr-endocrine' },
            ],
          },
          { text: '临床评价计划 (CEP)', link: '/zh/eu_mdr/td/cep' },
          { text: 'CER 与数据收集报告', link: '/zh/eu_mdr/td/cer' },
          { text: 'PMCF 计划与报告', link: '/zh/eu_mdr/td/pmcf' },
          { text: 'SSCP', link: '/zh/eu_mdr/td/sscp' },
          { text: 'PMS 计划', link: '/zh/eu_mdr/td/pms' },
          { text: 'PSUR', link: '/zh/eu_mdr/td/psur' },
          { text: '技术文件封面信', link: '/zh/eu_mdr/td/cover-letter' },
        ],
      },
      {
        text: '法规与指令', link: '/zh/eu_mdr/regulations',
        collapsed: true,
        items: [
          { text: '第2条 — 定义', link: '/zh/eu_mdr/regulations/art-2-definitions' },
          { text: '第10条 — 制造商一般义务', link: '/zh/eu_mdr/regulations/art-10-manufacturer-obligations' },
          { text: '第52条 — 合规评估程序', link: '/zh/eu_mdr/regulations/art-52-conformity-assessment' },
          { text: '附件I — GSPR', link: '/zh/eu_mdr/regulations/annex-i-gspr' },
          { text: '附件II — 技术文件', link: '/zh/eu_mdr/regulations/annex-ii-technical-documentation' },
          { text: '附件III — PMS技术文件', link: '/zh/eu_mdr/regulations/annex-iii-pms' },
          { text: '附件XIV — 临床评价', link: '/zh/eu_mdr/regulations/annex-xiv-clinical-evaluation' },
          { text: '附件XV — 临床调查', link: '/zh/eu_mdr/regulations/annex-xv-clinical-investigations' },
          { text: '修正案汇总', link: '/zh/eu_mdr/regulations/amendments' },
        ],
      },
      {
        text: '协调标准 (65)', link: '/zh/eu_mdr/standards',
        collapsed: true,
        items: [
          { text: '质量管理', link: '/zh/eu_mdr/standards/quality-management' },
          { text: '风险管理', link: '/zh/eu_mdr/standards/risk-management' },
          { text: '生物相容性', link: '/zh/eu_mdr/standards/biocompatibility' },
          { text: '电气安全与EMC', link: '/zh/eu_mdr/standards/electrical-safety' },
          { text: '灭菌与包装', link: '/zh/eu_mdr/standards/sterilization' },
          { text: '软件与可用性', link: '/zh/eu_mdr/standards/software' },
          { text: '标签与说明书', link: '/zh/eu_mdr/standards/labelling' },
          { text: '临床评价与临床调查', link: '/zh/eu_mdr/standards/clinical-investigation' },
          { text: '非有源外科植入物', link: '/zh/eu_mdr/standards/surgical-implants' },
          { text: '医用手套', link: '/zh/eu_mdr/standards/medical-gloves' },
          { text: '手术衣物与口罩', link: '/zh/eu_mdr/standards/surgical-textiles' },
          { text: '患者搬运设备', link: '/zh/eu_mdr/standards/patient-handling' },
          { text: '器械处理与再处理', link: '/zh/eu_mdr/standards/processing' },
          { text: '小口径连接器', link: '/zh/eu_mdr/standards/connectors' },
        ],
      },
      {
        text: '其他适用标准 (385)', link: '/zh/eu_mdr/other-standards',
        collapsed: true,
        items: [
          { text: '有源植入物', link: '/zh/eu_mdr/other-standards/active-implants' },
          { text: '增材制造(3D打印)', link: '/zh/eu_mdr/other-standards/additive-manufacturing' },
          { text: '麻醉设备', link: '/zh/eu_mdr/other-standards/anaesthesia' },
          { text: 'Annex XVI (非医疗目的)', link: '/zh/eu_mdr/other-standards/annex-xvi' },
          { text: '辅助技术', link: '/zh/eu_mdr/other-standards/assistive-technology' },
          { text: '听力学', link: '/zh/eu_mdr/other-standards/audiology' },
          { text: 'AI与机器学习', link: '/zh/eu_mdr/other-standards/ai-ml' },
          { text: '生物相容性', link: '/zh/eu_mdr/other-standards/biocompatibility' },
          { text: '生物来源材料', link: '/zh/eu_mdr/other-standards/biological-materials' },
          { text: '呼吸气路', link: '/zh/eu_mdr/other-standards/breathing-gas-pathways' },
          { text: '心血管', link: '/zh/eu_mdr/other-standards/cardiology' },
          { text: '临床调查', link: '/zh/eu_mdr/other-standards/clinical-investigation' },
          { text: '小口径连接器', link: '/zh/eu_mdr/other-standards/connectors' },
          { text: '网络安全', link: '/zh/eu_mdr/other-standards/cybersecurity' },
          { text: '牙科', link: '/zh/eu_mdr/other-standards/dental' },
          { text: '诊断成像', link: '/zh/eu_mdr/other-standards/diagnostic-imaging' },
          { text: '数字健康与可穿戴', link: '/zh/eu_mdr/other-standards/digital-health-wearables' },
          { text: '透析', link: '/zh/eu_mdr/other-standards/dialysis' },
          { text: '药械组合', link: '/zh/eu_mdr/other-standards/drug-device-combination' },
          { text: '电气安全与EMC', link: '/zh/eu_mdr/other-standards/electrical-safety' },
          { text: '内窥镜', link: '/zh/eu_mdr/other-standards/endoscopy' },
          { text: '环境测试', link: '/zh/eu_mdr/other-standards/environmental-testing' },
          { text: '家用医疗', link: '/zh/eu_mdr/other-standards/home-healthcare' },
          { text: '植入材料', link: '/zh/eu_mdr/other-standards/implant-materials' },
          { text: '植入物测试', link: '/zh/eu_mdr/other-standards/implant-testing' },
          { text: '输液与输血', link: '/zh/eu_mdr/other-standards/infusion-transfusion' },
          { text: '体外诊断', link: '/zh/eu_mdr/other-standards/ivd' },
          { text: '标签与符号', link: '/zh/eu_mdr/other-standards/labelling' },
          { text: '激光手术', link: '/zh/eu_mdr/other-standards/laser-surgery' },
          { text: '碎石术', link: '/zh/eu_mdr/other-standards/lithotripsy' },
          { text: '机械测试', link: '/zh/eu_mdr/other-standards/mechanical-testing' },
          { text: '医用手套', link: '/zh/eu_mdr/other-standards/medical-gloves' },
          { text: 'MRI 安全', link: '/zh/eu_mdr/other-standards/mri-safety' },
          { text: '针头与注射器', link: '/zh/eu_mdr/other-standards/needles-syringes' },
          { text: '新生儿', link: '/zh/eu_mdr/other-standards/neonatal' },
          { text: '神经学', link: '/zh/eu_mdr/other-standards/neurology' },
          { text: '核医学', link: '/zh/eu_mdr/other-standards/nuclear-medicine' },
          { text: '眼科', link: '/zh/eu_mdr/other-standards/ophthalmic' },
          { text: '包装', link: '/zh/eu_mdr/other-standards/packaging' },
          { text: '患者监护', link: '/zh/eu_mdr/other-standards/patient-monitoring' },
          { text: '患者加温', link: '/zh/eu_mdr/other-standards/patient-warming' },
          { text: '光疗', link: '/zh/eu_mdr/other-standards/phototherapy' },
          { text: '物理治疗', link: '/zh/eu_mdr/other-standards/physiotherapy' },
          { text: '即时检验(POCT)', link: '/zh/eu_mdr/other-standards/point-of-care-testing' },
          { text: '上市后监督', link: '/zh/eu_mdr/other-standards/pms' },
          { text: '防护设备', link: '/zh/eu_mdr/other-standards/ppe-barrier' },
          { text: '质量管理', link: '/zh/eu_mdr/other-standards/quality-management' },
          { text: '辐射防护', link: '/zh/eu_mdr/other-standards/radiation-protection' },
          { text: '法规参考', link: '/zh/eu_mdr/other-standards/regulatory-references' },
          { text: '再处理', link: '/zh/eu_mdr/other-standards/reprocessing' },
          { text: '呼吸与麻醉', link: '/zh/eu_mdr/other-standards/respiratory-anaesthesia' },
          { text: '风险管理', link: '/zh/eu_mdr/other-standards/risk-management' },
          { text: '手术机器人', link: '/zh/eu_mdr/other-standards/robotic-surgery' },
          { text: '软件与可用性', link: '/zh/eu_mdr/other-standards/software' },
          { text: '灭菌', link: '/zh/eu_mdr/other-standards/sterilization' },
          { text: '外科植入物', link: '/zh/eu_mdr/other-standards/surgical-implants' },
          { text: '手术器械', link: '/zh/eu_mdr/other-standards/surgical-instruments' },
          { text: '治疗超声', link: '/zh/eu_mdr/other-standards/therapeutic-ultrasound' },
          { text: '组织工程', link: '/zh/eu_mdr/other-standards/tissue-engineering' },
          { text: '泌尿生殖', link: '/zh/eu_mdr/other-standards/urogenital' },
          { text: '可用性工程', link: '/zh/eu_mdr/other-standards/usability' },
          { text: '血管器械', link: '/zh/eu_mdr/other-standards/vascular-devices' },
          { text: '伤口护理', link: '/zh/eu_mdr/other-standards/wound-care' },
        ],
      },
      {
        text: 'MDCG 指南', link: '/zh/eu_mdr/mdcg',
        collapsed: true,
        items: [
          { text: '临床评价 — 等同性', link: '/zh/eu_mdr/mdcg/mdcg-2020-5' },
          { text: '遗留器械临床证据', link: '/zh/eu_mdr/mdcg/mdcg-2020-6' },
          { text: 'PMCF计划模板', link: '/zh/eu_mdr/mdcg/mdcg-2020-7' },
          { text: 'PMCF评估报告模板', link: '/zh/eu_mdr/mdcg/mdcg-2020-8' },
          { text: 'SSCP指南', link: '/zh/eu_mdr/mdcg/mdcg-2019-9' },
          { text: 'PSUR指南', link: '/zh/eu_mdr/mdcg/mdcg-2022-21' },
          { text: '器械分类指南 (rev.1)', link: '/zh/eu_mdr/mdcg/mdcg-2021-24' },
          { text: '软件临床评价', link: '/zh/eu_mdr/mdcg/mdcg-2020-1' },
          { text: '网络安全指南', link: '/zh/eu_mdr/mdcg/mdcg-2019-16' },
          { text: '临床调查豁免', link: '/zh/eu_mdr/mdcg/mdcg-2023-7' },
          { text: 'CIP内容指南', link: '/zh/eu_mdr/mdcg/mdcg-2024-3' },
          { text: 'MDR/IVDR与AI法案', link: '/zh/eu_mdr/mdcg/mdcg-2025-6' },
          { text: '突破性器械(BtX)', link: '/zh/eu_mdr/mdcg/mdcg-2025-9' },
        ],
      },
      { text: 'TEAM-NB 立场文件', link: '/zh/eu_mdr/team_nb' },
    ],
    '/zh/eu_ivdr/': [
      { text: 'EU IVDR 概述', link: '/zh/eu_ivdr/' },
      {
        text: '技术文件 (BPG IVDR V2)', link: '/zh/eu_ivdr/td/',
        collapsed: false,
        items: [
          { text: '器械描述与规格', link: '/zh/eu_ivdr/td/device-description' },
          { text: '制造商提供的信息', link: '/zh/eu_ivdr/td/information-supplied' },
          { text: '设计与制造', link: '/zh/eu_ivdr/td/design-manufacturing' },
          { text: 'GSPR 检查表', link: '/zh/eu_ivdr/td/gspr' },
          { text: '风险管理', link: '/zh/eu_ivdr/td/risk-management' },
          {
            text: '验证与确认 (V&V)', link: '/zh/eu_ivdr/td/verification-validation',
            collapsed: true,
            items: [
              { text: 'V&V 总览', link: '/zh/eu_ivdr/td/vv/' },
              { text: '稳定性（试剂）', link: '/zh/eu_ivdr/td/vv/stability' },
              { text: '计量溯源', link: '/zh/eu_ivdr/td/vv/metrological-traceability' },
              { text: '可用性/人因工程', link: '/zh/eu_ivdr/td/vv/usability' },
              { text: '化学/物理/生物特性', link: '/zh/eu_ivdr/td/vv/chemical-physical-biological' },
              { text: '软件与网络安全', link: '/zh/eu_ivdr/td/vv/software' },
            ],
          },
          { text: '性能评价 (PEP/PER)', link: '/zh/eu_ivdr/td/performance-evaluation' },
          { text: 'PMPF 计划与报告', link: '/zh/eu_ivdr/td/pmpf' },
          { text: 'SSP', link: '/zh/eu_ivdr/td/ssp' },
          { text: 'PMS', link: '/zh/eu_ivdr/td/pms' },
          { text: '伴随诊断 (CDx)', link: '/zh/eu_ivdr/td/companion-diagnostics' },
          { text: 'TD 封面信 / 提交通则', link: '/zh/eu_ivdr/td/cover-letter' },
        ],
      },
    ],
    '/zh/fda/': [
      { text: 'FDA 概述', link: '/zh/fda/' },
      { text: '510(k) 审批时限', link: '/zh/fda/510k-timeline' },
      {
        text: '510(k) 提交 (eSTAR)', link: '/zh/fda/td/',
        collapsed: true,
        items: [
          { text: '提交概述', link: '/zh/fda/td/submission-overview' },
        ],
      },
      { text: '法规 (21 CFR)', link: '/zh/fda/regulations' },
      { text: '共识标准', link: '/zh/fda/standards' },
      {
        text: '指南文件', link: '/zh/fda/guidance',
        collapsed: true,
        items: [
          { text: '目录索引', link: '/zh/fda/guidance' },
          { text: '数字健康与网络安全', link: '/zh/fda/guidance#digital_health_cyber' },
          { text: '上市前', link: '/zh/fda/guidance#premarket' },
          { text: '质量 / 生产制造', link: '/zh/fda/guidance#quality_manufacturing' },
          { text: '体外诊断', link: '/zh/fda/guidance#ivd' },
          { text: '标签标识 / UDI', link: '/zh/fda/guidance#labeling_udi' },
          { text: '上市后', link: '/zh/fda/guidance#postmarket' },
          { text: '辐射 / 影像', link: '/zh/fda/guidance#radiation_imaging' },
          { text: '临床 / RWE', link: '/zh/fda/guidance#clinical_rwe' },
          { text: '其他', link: '/zh/fda/guidance#other' },
          { text: '英文目录', link: '/en/fda/guidance' },
        ],
      },
    ],
    '/zh/nmpa/': [
      { text: 'NMPA 概述', link: '/zh/nmpa/' },
      { text: '注册审批时限', link: '/zh/nmpa/registration-timeline' },
      {
        text: '注册申报资料', link: '/zh/nmpa/td/',
        collapsed: true,
        items: [
          { text: '情形总览（首次注册）', link: '/zh/nmpa/td/' },
          { text: '变更注册', link: '/zh/nmpa/td/change-registration' },
          { text: '变更备案', link: '/zh/nmpa/td/change-filing' },
          { text: '延续注册', link: '/zh/nmpa/td/renewal' },
          { text: '第一类备案', link: '/zh/nmpa/td/class-i-filing' },
          { text: '创新特别审查', link: '/zh/nmpa/td/innovation-special-review' },
          { text: '第1章：监管信息', link: '/zh/nmpa/td/regulatory-info' },
          { text: '第2章：综述资料', link: '/zh/nmpa/td/product-summary' },
          { text: '第3章：非临床资料', link: '/zh/nmpa/td/non-clinical' },
          { text: '第4章：临床评价资料', link: '/zh/nmpa/td/clinical-evaluation' },
          { text: '第5章：说明书和标签', link: '/zh/nmpa/td/ifu-labels' },
          { text: '第6章：质量管理体系文件', link: '/zh/nmpa/td/qms' },
        ],
      },
      { text: '法规规章', link: '/zh/nmpa/regulations' },
      {
        text: 'GB/YY 标准 (2,100)', link: '/zh/nmpa/standards',
        collapsed: true,
        items: [
          { text: '通用技术领域 (228)', link: '/zh/nmpa/standards/general' },
          { text: '专业技术领域 (1,872)', link: '/zh/nmpa/standards/professional' },
        ],
      },
      { text: '指导原则', link: '/zh/nmpa/guidance' },
      {
        text: '分类目录 (1,142)', link: '/zh/nmpa/classification',
        collapsed: true,
        items: [
          { text: '01 有源手术器械', link: '/zh/nmpa/classification/01' },
          { text: '02 无源手术器械', link: '/zh/nmpa/classification/02' },
          { text: '03 神经和心血管手术器械', link: '/zh/nmpa/classification/03' },
          { text: '04 骨科手术器械', link: '/zh/nmpa/classification/04' },
          { text: '05 放射治疗器械', link: '/zh/nmpa/classification/05' },
          { text: '06 医用成像器械', link: '/zh/nmpa/classification/06' },
          { text: '07 医用诊察和监护器械', link: '/zh/nmpa/classification/07' },
          { text: '08 呼吸、麻醉和急救器械', link: '/zh/nmpa/classification/08' },
          { text: '09 物理治疗器械', link: '/zh/nmpa/classification/09' },
          { text: '10 输血、透析和体外循环器械', link: '/zh/nmpa/classification/10' },
          { text: '11 医疗器械消毒灭菌器械', link: '/zh/nmpa/classification/11' },
          { text: '12 有源植入器械', link: '/zh/nmpa/classification/12' },
          { text: '13 无源植入器械', link: '/zh/nmpa/classification/13' },
          { text: '14 注输、护理和防护器械', link: '/zh/nmpa/classification/14' },
          { text: '15 患者承载器械', link: '/zh/nmpa/classification/15' },
          { text: '16 眼科器械', link: '/zh/nmpa/classification/16' },
          { text: '17 口腔科器械', link: '/zh/nmpa/classification/17' },
          { text: '18 妇产科、辅助生殖和避孕器械', link: '/zh/nmpa/classification/18' },
          { text: '19 医用康复器械', link: '/zh/nmpa/classification/19' },
          { text: '20 中医器械', link: '/zh/nmpa/classification/20' },
          { text: '21 医用软件', link: '/zh/nmpa/classification/21' },
          { text: '22 临床检验器械', link: '/zh/nmpa/classification/22' },
        ],
      },
    ],
    '/zh/shared/': [
      { text: '通用标准', link: '/zh/shared/standards' },
      {
        text: 'IMDRF 技术文件', link: '/zh/shared/imdrf',
        collapsed: true,
        items: [
          { text: 'SaMD 软件医疗器械', link: '/zh/shared/imdrf/samd' },
          { text: 'AI/ML 人工智能', link: '/zh/shared/imdrf/aiml' },
          { text: '网络安全', link: '/zh/shared/imdrf/cyber' },
          { text: 'UDI 唯一标识', link: '/zh/shared/imdrf/udi' },
          { text: 'MDSAP 单一审核', link: '/zh/shared/imdrf/mdsap' },
          { text: 'GRRP 监管审查', link: '/zh/shared/imdrf/grrp' },
          { text: '临床证据与评价', link: '/zh/shared/imdrf/clinical' },
          { text: '不良事件报告', link: '/zh/shared/imdrf/ae' },
          { text: '监管提交', link: '/zh/shared/imdrf/rps' },
          { text: '个性化医疗器械', link: '/zh/shared/imdrf/pmd' },
          { text: 'IVD 体外诊断', link: '/zh/shared/imdrf/ivd' },
          { text: '标准', link: '/zh/shared/imdrf/standards' },
        ],
      },
    ],
    '/zh/hub/': [
      { text: 'Reguverse Hub', link: '/zh/hub/' },
    ],
    '/zh/learn/': [
      { text: 'Reguverse Learn', link: '/zh/learn/' },
    ],
    '/zh/news/': [
      { text: '法规速递', link: '/zh/news/' },
      { text: 'EU MDR', link: '/zh/news/eu_mdr' },
      { text: 'FDA', link: '/zh/news/fda' },
      { text: 'NMPA', link: '/zh/news/nmpa' },
      { text: 'UK MHRA', link: '/zh/news/uk_mhra' },
      { text: 'Health Canada', link: '/zh/news/canada' },
      { text: 'Australia TGA', link: '/zh/news/australia_tga' },
      { text: 'Japan PMDA', link: '/zh/news/japan_pmda' },
      { text: 'Korea MFDS', link: '/zh/news/korea_mfds' },
      { text: 'Swissmedic', link: '/zh/news/switzerland' },
      { text: 'Brazil ANVISA', link: '/zh/news/brazil_anvisa' },
      { text: 'Saudi SFDA', link: '/zh/news/saudi_sfda' },
      { text: 'Singapore HSA', link: '/zh/news/singapore_hsa' },
      { text: 'India CDSCO', link: '/zh/news/india_cdsco' },
      { text: 'Mexico COFEPRIS', link: '/zh/news/mexico_cofepris' },
      { text: 'Argentina ANMAT', link: '/zh/news/argentina_anmat' },
      { text: 'Taiwan TFDA', link: '/zh/news/taiwan_tfda' },
      { text: 'New Zealand Medsafe', link: '/zh/news/newzealand_medsafe' },
      { text: 'Indonesia BPOM', link: '/zh/news/indonesia_bpom' },
      { text: 'Malaysia MDA', link: '/zh/news/malaysia_mda' },
      { text: 'Thailand FDA', link: '/zh/news/thailand_fda' },
      { text: 'Israel MOH', link: '/zh/news/israel_moh' },
      { text: 'Hong Kong MDCO', link: '/zh/news/hongkong_mdco' },
    ],
  },
  dynamicSidebar,
)

export default defineConfig({
  title: '小安 知识库',
  description: 'Open regulatory knowledge base for medical device compliance',
  srcDir: '.',
  ignoreDeadLinks: true,
  markdown: {
    image: {
      lazyLoading: true
    },
    config: (md) => {
      const defaultRender = md.renderer.rules.image ||
        function (tokens: any, idx: any, options: any, _env: any, self: any) {
          return self.renderToken(tokens, idx, options)
        }
      md.renderer.rules.image = (tokens, idx, options, env, self) => {
        const token = tokens[idx]
        const src = token.attrGet('src') || ''
        if (src.startsWith('/images/')) {
          token.attrSet('src', `https://docs.team-ra.org${src}`)
        }
        return defaultRender(tokens, idx, options, env, self)
      }
    }
  },

  locales: {
    root: {
      label: 'English',
      lang: 'en',
      link: '/en/',
      themeConfig: {
        nav: [
          { text: 'Home', link: '/' },
          {
            text: 'EU',
            items: [
              { text: 'EU MDR', link: '/en/eu_mdr/' },
              { text: 'EU IVDR', link: '/en/eu_ivdr/' },
            ],
          },
          { text: 'FDA', link: '/en/fda/' },
          { text: 'NMPA', link: '/en/nmpa/' },
          {
            text: 'More',
            items: [
              { text: 'International', link: '/en/shared/standards' },
              { text: 'News', link: '/en/news/' },
              { text: 'Insights', link: '/en/insights/' },
              { text: 'Hub', link: '/en/hub/' },
              { text: 'Learn', link: '/en/learn/' },
              { text: 'Get Started', link: '/en/get-started' },
              { text: 'Contact', link: '/en/contact' },
            ],
          },
        ],
        sidebar: Object.assign(
          {
            '/en/eu_mdr/': [
              { text: 'EU MDR Overview', link: '/en/eu_mdr/' },
              {
                text: 'Technical Documentation (BPG Rev.4)', link: '/en/eu_mdr/td/',
                collapsed: true,
                items: [
                  { text: 'Device Description & Specification', link: '/en/eu_mdr/td/device-description' },
                  { text: 'Information Supplied by Manufacturer', link: '/en/eu_mdr/td/information-supplied' },
                  { text: 'Design & Manufacturing', link: '/en/eu_mdr/td/design-manufacturing' },
                  { text: 'GSPR Checklist', link: '/en/eu_mdr/td/gspr' },
                  { text: 'Risk Management', link: '/en/eu_mdr/td/risk-management' },
                  {
                    text: 'Verification & Validation (V&V)', link: '/en/eu_mdr/td/verification-validation',
                    collapsed: true,
                    items: [
                      { text: 'V&V Overview', link: '/en/eu_mdr/td/vv/' },
                      { text: 'Design V&V', link: '/en/eu_mdr/td/vv/design-vv' },
                      { text: 'Biocompatibility', link: '/en/eu_mdr/td/vv/biocompatibility' },
                      { text: 'Electrical Safety & EMC', link: '/en/eu_mdr/td/vv/electrical-safety-emc' },
                      { text: 'Software V&V (IEC 62304)', link: '/en/eu_mdr/td/vv/software-vv' },
                      { text: 'Cybersecurity', link: '/en/eu_mdr/td/vv/cybersecurity' },
                      { text: 'Stability & Shelf-life', link: '/en/eu_mdr/td/vv/stability-shelf-life' },
                      { text: 'Packaging', link: '/en/eu_mdr/td/vv/packaging' },
                      { text: 'Sterilization', link: '/en/eu_mdr/td/vv/sterilization' },
                      { text: 'Usability / Human Factors', link: '/en/eu_mdr/td/vv/usability' },
                      { text: 'FDA HF Summary (2026)', link: '/en/eu_mdr/td/vv/usability-fda-hf' },
                      { text: 'Device Lifetime', link: '/en/eu_mdr/td/vv/device-lifetime' },
                      { text: 'Measuring / Diagnostic', link: '/en/eu_mdr/td/vv/measuring-diagnostic' },
                      { text: 'MRI Safety', link: '/en/eu_mdr/td/vv/mri-safety' },
                      { text: 'Interoperability', link: '/en/eu_mdr/td/vv/interoperability' },
                      { text: 'Reprocessing', link: '/en/eu_mdr/td/vv/reprocessing' },
                      { text: 'Drug-Device Combination', link: '/en/eu_mdr/td/vv/drug-device' },
                      { text: 'Animal Tissue', link: '/en/eu_mdr/td/vv/animal-tissue' },
                      { text: 'Human Tissue', link: '/en/eu_mdr/td/vv/human-tissue' },
                      { text: 'Absorbed Substances', link: '/en/eu_mdr/td/vv/absorbed-substances' },
                      { text: 'CMR / Endocrine Disrupting', link: '/en/eu_mdr/td/vv/cmr-endocrine' },
                    ],
                  },
                  { text: 'Clinical Evaluation Plan (CEP)', link: '/en/eu_mdr/td/cep' },
                  { text: 'CER & Data Collection Report', link: '/en/eu_mdr/td/cer' },
                  { text: 'PMCF Plan & Report', link: '/en/eu_mdr/td/pmcf' },
                  { text: 'SSCP', link: '/en/eu_mdr/td/sscp' },
                  { text: 'PMS Plan', link: '/en/eu_mdr/td/pms' },
                  { text: 'PSUR', link: '/en/eu_mdr/td/psur' },
                  { text: 'TD Cover Letter', link: '/en/eu_mdr/td/cover-letter' },
                ],
              },
              {
                text: 'Regulations & Directives', link: '/en/eu_mdr/regulations',
                collapsed: true,
                items: [
                  { text: 'Article 2 — Definitions', link: '/en/eu_mdr/regulations/art-2-definitions' },
                  { text: 'Article 10 — Manufacturer Obligations', link: '/en/eu_mdr/regulations/art-10-manufacturer-obligations' },
                  { text: 'Article 52 — Conformity Assessment', link: '/en/eu_mdr/regulations/art-52-conformity-assessment' },
                  { text: 'Annex I — GSPR', link: '/en/eu_mdr/regulations/annex-i-gspr' },
                  { text: 'Annex II — Technical Documentation', link: '/en/eu_mdr/regulations/annex-ii-technical-documentation' },
                  { text: 'Annex III — PMS Documentation', link: '/en/eu_mdr/regulations/annex-iii-pms' },
                  { text: 'Annex XIV — Clinical Evaluation', link: '/en/eu_mdr/regulations/annex-xiv-clinical-evaluation' },
                  { text: 'Annex XV — Clinical Investigations', link: '/en/eu_mdr/regulations/annex-xv-clinical-investigations' },
                  { text: 'Amendments Summary', link: '/en/eu_mdr/regulations/amendments' },
                ],
              },
              {
                text: 'Harmonised Standards (65)', link: '/en/eu_mdr/standards',
                collapsed: true,
                items: [
                  { text: 'Quality Management', link: '/en/eu_mdr/standards/quality-management' },
                  { text: 'Risk Management', link: '/en/eu_mdr/standards/risk-management' },
                  { text: 'Biocompatibility', link: '/en/eu_mdr/standards/biocompatibility' },
                  { text: 'Electrical Safety & EMC', link: '/en/eu_mdr/standards/electrical-safety' },
                  { text: 'Sterilization & Packaging', link: '/en/eu_mdr/standards/sterilization' },
                  { text: 'Software & Usability', link: '/en/eu_mdr/standards/software' },
                  { text: 'Labelling & IFU', link: '/en/eu_mdr/standards/labelling' },
                  { text: 'Clinical Investigation', link: '/en/eu_mdr/standards/clinical-investigation' },
                  { text: 'Non-Active Surgical Implants', link: '/en/eu_mdr/standards/surgical-implants' },
                  { text: 'Medical Gloves', link: '/en/eu_mdr/standards/medical-gloves' },
                  { text: 'Surgical Clothing & Masks', link: '/en/eu_mdr/standards/surgical-textiles' },
                  { text: 'Patient Handling Equipment', link: '/en/eu_mdr/standards/patient-handling' },
                  { text: 'Device Processing', link: '/en/eu_mdr/standards/processing' },
                  { text: 'Small-Bore Connectors', link: '/en/eu_mdr/standards/connectors' },
                ],
              },
              {
                text: 'Other Standards (385)', link: '/en/eu_mdr/other-standards',
                collapsed: true,
                items: [
                  { text: 'Active Implants', link: '/en/eu_mdr/other-standards/active-implants' },
                  { text: 'Additive Manufacturing (3D Printing)', link: '/en/eu_mdr/other-standards/additive-manufacturing' },
                  { text: 'Anaesthesia', link: '/en/eu_mdr/other-standards/anaesthesia' },
                  { text: 'Annex XVI (Non-Medical Purpose)', link: '/en/eu_mdr/other-standards/annex-xvi' },
                  { text: 'Assistive Technology', link: '/en/eu_mdr/other-standards/assistive-technology' },
                  { text: 'Audiology', link: '/en/eu_mdr/other-standards/audiology' },
                  { text: 'AI & Machine Learning', link: '/en/eu_mdr/other-standards/ai-ml' },
                  { text: 'Biocompatibility', link: '/en/eu_mdr/other-standards/biocompatibility' },
                  { text: 'Biological Materials', link: '/en/eu_mdr/other-standards/biological-materials' },
                  { text: 'Breathing Gas Pathways', link: '/en/eu_mdr/other-standards/breathing-gas-pathways' },
                  { text: 'Cardiology', link: '/en/eu_mdr/other-standards/cardiology' },
                  { text: 'Clinical Investigation', link: '/en/eu_mdr/other-standards/clinical-investigation' },
                  { text: 'Connectors', link: '/en/eu_mdr/other-standards/connectors' },
                  { text: 'Cybersecurity', link: '/en/eu_mdr/other-standards/cybersecurity' },
                  { text: 'Dental', link: '/en/eu_mdr/other-standards/dental' },
                  { text: 'Diagnostic Imaging', link: '/en/eu_mdr/other-standards/diagnostic-imaging' },
                  { text: 'Digital Health & Wearables', link: '/en/eu_mdr/other-standards/digital-health-wearables' },
                  { text: 'Dialysis', link: '/en/eu_mdr/other-standards/dialysis' },
                  { text: 'Drug-Device Combination', link: '/en/eu_mdr/other-standards/drug-device-combination' },
                  { text: 'Electrical Safety & EMC', link: '/en/eu_mdr/other-standards/electrical-safety' },
                  { text: 'Endoscopy', link: '/en/eu_mdr/other-standards/endoscopy' },
                  { text: 'Environmental Testing', link: '/en/eu_mdr/other-standards/environmental-testing' },
                  { text: 'Home Healthcare', link: '/en/eu_mdr/other-standards/home-healthcare' },
                  { text: 'Implant Materials', link: '/en/eu_mdr/other-standards/implant-materials' },
                  { text: 'Implant Testing', link: '/en/eu_mdr/other-standards/implant-testing' },
                  { text: 'Infusion & Transfusion', link: '/en/eu_mdr/other-standards/infusion-transfusion' },
                  { text: 'In Vitro Diagnostics', link: '/en/eu_mdr/other-standards/ivd' },
                  { text: 'Labelling & Symbols', link: '/en/eu_mdr/other-standards/labelling' },
                  { text: 'Laser Surgery', link: '/en/eu_mdr/other-standards/laser-surgery' },
                  { text: 'Lithotripsy', link: '/en/eu_mdr/other-standards/lithotripsy' },
                  { text: 'Mechanical Testing', link: '/en/eu_mdr/other-standards/mechanical-testing' },
                  { text: 'Medical Gloves', link: '/en/eu_mdr/other-standards/medical-gloves' },
                  { text: 'MRI Safety', link: '/en/eu_mdr/other-standards/mri-safety' },
                  { text: 'Needles & Syringes', link: '/en/eu_mdr/other-standards/needles-syringes' },
                  { text: 'Neonatal', link: '/en/eu_mdr/other-standards/neonatal' },
                  { text: 'Neurology', link: '/en/eu_mdr/other-standards/neurology' },
                  { text: 'Nuclear Medicine', link: '/en/eu_mdr/other-standards/nuclear-medicine' },
                  { text: 'Ophthalmic', link: '/en/eu_mdr/other-standards/ophthalmic' },
                  { text: 'Packaging', link: '/en/eu_mdr/other-standards/packaging' },
                  { text: 'Patient Monitoring', link: '/en/eu_mdr/other-standards/patient-monitoring' },
                  { text: 'Patient Warming', link: '/en/eu_mdr/other-standards/patient-warming' },
                  { text: 'Phototherapy', link: '/en/eu_mdr/other-standards/phototherapy' },
                  { text: 'Physiotherapy', link: '/en/eu_mdr/other-standards/physiotherapy' },
                  { text: 'Point-of-Care Testing', link: '/en/eu_mdr/other-standards/point-of-care-testing' },
                  { text: 'Post-Market Surveillance', link: '/en/eu_mdr/other-standards/pms' },
                  { text: 'PPE & Barrier', link: '/en/eu_mdr/other-standards/ppe-barrier' },
                  { text: 'Quality Management', link: '/en/eu_mdr/other-standards/quality-management' },
                  { text: 'Radiation Protection', link: '/en/eu_mdr/other-standards/radiation-protection' },
                  { text: 'Regulatory References', link: '/en/eu_mdr/other-standards/regulatory-references' },
                  { text: 'Reprocessing', link: '/en/eu_mdr/other-standards/reprocessing' },
                  { text: 'Respiratory & Anaesthesia', link: '/en/eu_mdr/other-standards/respiratory-anaesthesia' },
                  { text: 'Risk Management', link: '/en/eu_mdr/other-standards/risk-management' },
                  { text: 'Robotic Surgery', link: '/en/eu_mdr/other-standards/robotic-surgery' },
                  { text: 'Software & Usability', link: '/en/eu_mdr/other-standards/software' },
                  { text: 'Sterilization', link: '/en/eu_mdr/other-standards/sterilization' },
                  { text: 'Surgical Implants', link: '/en/eu_mdr/other-standards/surgical-implants' },
                  { text: 'Surgical Instruments', link: '/en/eu_mdr/other-standards/surgical-instruments' },
                  { text: 'Therapeutic Ultrasound', link: '/en/eu_mdr/other-standards/therapeutic-ultrasound' },
                  { text: 'Tissue Engineering', link: '/en/eu_mdr/other-standards/tissue-engineering' },
                  { text: 'Urogenital', link: '/en/eu_mdr/other-standards/urogenital' },
                  { text: 'Usability Engineering', link: '/en/eu_mdr/other-standards/usability' },
                  { text: 'Vascular Devices', link: '/en/eu_mdr/other-standards/vascular-devices' },
                  { text: 'Wound Care', link: '/en/eu_mdr/other-standards/wound-care' },
                ],
              },
              {
                text: 'MDCG Guidance', link: '/en/eu_mdr/mdcg',
                collapsed: true,
                items: [
                  { text: 'Clinical Evaluation — Equivalence', link: '/en/eu_mdr/mdcg/mdcg-2020-5' },
                  { text: 'Legacy Devices Clinical Evidence', link: '/en/eu_mdr/mdcg/mdcg-2020-6' },
                  { text: 'PMCF Plan Template', link: '/en/eu_mdr/mdcg/mdcg-2020-7' },
                  { text: 'PMCF Evaluation Report Template', link: '/en/eu_mdr/mdcg/mdcg-2020-8' },
                  { text: 'SSCP Guidance', link: '/en/eu_mdr/mdcg/mdcg-2019-9' },
                  { text: 'PSUR Guidance', link: '/en/eu_mdr/mdcg/mdcg-2022-21' },
                  { text: 'Device Classification (rev.1)', link: '/en/eu_mdr/mdcg/mdcg-2021-24' },
                  { text: 'Software Clinical Evaluation', link: '/en/eu_mdr/mdcg/mdcg-2020-1' },
                  { text: 'Cybersecurity Guidance', link: '/en/eu_mdr/mdcg/mdcg-2019-16' },
                  { text: 'Clinical Investigation Exemptions', link: '/en/eu_mdr/mdcg/mdcg-2023-7' },
                  { text: 'CIP Content Guidance', link: '/en/eu_mdr/mdcg/mdcg-2024-3' },
                  { text: 'MDR/IVDR & AI Act', link: '/en/eu_mdr/mdcg/mdcg-2025-6' },
                  { text: 'Breakthrough Devices (BtX)', link: '/en/eu_mdr/mdcg/mdcg-2025-9' },
                ],
              },
              { text: 'TEAM-NB Position Papers', link: '/en/eu_mdr/team_nb' },
              { text: 'Certification Timeline', link: '/en/eu_mdr/certification-timeline' },
            ],
            '/en/eu_ivdr/': [
              { text: 'EU IVDR Overview', link: '/en/eu_ivdr/' },
              {
                text: 'Technical Documentation (BPG IVDR V2)', link: '/en/eu_ivdr/td/',
                collapsed: false,
                items: [
                  { text: 'Device Description & Specification', link: '/en/eu_ivdr/td/device-description' },
                  { text: 'Information Supplied by Manufacturer', link: '/en/eu_ivdr/td/information-supplied' },
                  { text: 'Design & Manufacturing', link: '/en/eu_ivdr/td/design-manufacturing' },
                  { text: 'GSPR Checklist', link: '/en/eu_ivdr/td/gspr' },
                  { text: 'Risk Management', link: '/en/eu_ivdr/td/risk-management' },
                  {
                    text: 'Verification & Validation (V&V)', link: '/en/eu_ivdr/td/verification-validation',
                    collapsed: true,
                    items: [
                      { text: 'V&V Overview', link: '/en/eu_ivdr/td/vv/' },
                      { text: 'Stability (reagents)', link: '/en/eu_ivdr/td/vv/stability' },
                      { text: 'Metrological Traceability', link: '/en/eu_ivdr/td/vv/metrological-traceability' },
                      { text: 'Usability / Human Factors', link: '/en/eu_ivdr/td/vv/usability' },
                      { text: 'Chemical / Physical / Biological', link: '/en/eu_ivdr/td/vv/chemical-physical-biological' },
                      { text: 'Software & Cybersecurity', link: '/en/eu_ivdr/td/vv/software' },
                    ],
                  },
                  { text: 'Performance Evaluation (PEP/PER)', link: '/en/eu_ivdr/td/performance-evaluation' },
                  { text: 'PMPF Plan & Report', link: '/en/eu_ivdr/td/pmpf' },
                  { text: 'SSP', link: '/en/eu_ivdr/td/ssp' },
                  { text: 'PMS', link: '/en/eu_ivdr/td/pms' },
                  { text: 'Companion Diagnostics', link: '/en/eu_ivdr/td/companion-diagnostics' },
                  { text: 'TD Cover Letter / Submission', link: '/en/eu_ivdr/td/cover-letter' },
                ],
              },
            ],
            '/en/fda/': [
              { text: 'FDA Overview', link: '/en/fda/' },
              { text: '510(k) Review Timeline', link: '/en/fda/510k-timeline' },
              {
                text: '510(k) Submission (eSTAR)', link: '/en/fda/td/',
                collapsed: true,
                items: [
                  { text: 'Submission Overview', link: '/en/fda/td/submission-overview' },
                ],
              },
              { text: 'Regulations (21 CFR)', link: '/en/fda/regulations' },
              { text: 'Consensus Standards', link: '/en/fda/standards' },
              {
                text: 'Guidance Documents (CDRH Final)', link: '/en/fda/guidance',
                collapsed: true,
                items: [
                  { text: 'Catalog index', link: '/en/fda/guidance' },
                  { text: 'Digital Health & Cybersecurity', link: '/en/fda/guidance#digital_health_cyber' },
                  { text: 'Premarket', link: '/en/fda/guidance#premarket' },
                  { text: 'Quality / Manufacturing', link: '/en/fda/guidance#quality_manufacturing' },
                  { text: 'IVD', link: '/en/fda/guidance#ivd' },
                  { text: 'Labeling / UDI', link: '/en/fda/guidance#labeling_udi' },
                  { text: 'Postmarket', link: '/en/fda/guidance#postmarket' },
                  { text: 'Radiation / Imaging', link: '/en/fda/guidance#radiation_imaging' },
                  { text: 'Clinical / RWE', link: '/en/fda/guidance#clinical_rwe' },
                  { text: 'Other', link: '/en/fda/guidance#other' },
                ],
              },
            ],
            '/en/nmpa/': [
              { text: 'NMPA Overview', link: '/en/nmpa/' },
              {
                text: 'Technical Documentation', link: '/en/nmpa/td/',
                collapsed: true,
                items: [
                  { text: 'Scenario overview (initial)', link: '/en/nmpa/td/' },
                  { text: 'Change registration', link: '/en/nmpa/td/change-registration' },
                  { text: 'Change filing', link: '/en/nmpa/td/change-filing' },
                  { text: 'Renewal', link: '/en/nmpa/td/renewal' },
                  { text: 'Class I filing', link: '/en/nmpa/td/class-i-filing' },
                  { text: 'Innovation special review', link: '/en/nmpa/td/innovation-special-review' },
                  { text: 'Ch.1: Regulatory Information', link: '/en/nmpa/td/regulatory-info' },
                  { text: 'Ch.2: Product Summary', link: '/en/nmpa/td/product-summary' },
                  { text: 'Ch.3: Non-Clinical Data', link: '/en/nmpa/td/non-clinical' },
                  { text: 'Ch.4: Clinical Evaluation', link: '/en/nmpa/td/clinical-evaluation' },
                  { text: 'Ch.5: IFU & Labels', link: '/en/nmpa/td/ifu-labels' },
                  { text: 'Ch.6: QMS Documentation', link: '/en/nmpa/td/qms' },
                ],
              },
              { text: 'Regulations', link: '/en/nmpa/regulations' },
              {
                text: 'GB/YY Standards (2,100)', link: '/en/nmpa/standards',
                collapsed: true,
                items: [
                  { text: 'General Technical (228)', link: '/en/nmpa/standards/general' },
                  { text: 'Professional Technical (1,872)', link: '/en/nmpa/standards/professional' },
                ],
              },
              { text: 'Registration Timeline', link: '/en/nmpa/registration-timeline' },
              { text: 'Guidance Principles', link: '/en/nmpa/guidance' },
              {
                text: 'Classification (1,142)', link: '/en/nmpa/classification',
                collapsed: true,
                items: [
                  { text: '01 Active Surgical Instruments', link: '/en/nmpa/classification/01' },
                  { text: '02 Passive Surgical Instruments', link: '/en/nmpa/classification/02' },
                  { text: '03 Neurovascular Surgical Instruments', link: '/en/nmpa/classification/03' },
                  { text: '04 Orthopedic Surgical Instruments', link: '/en/nmpa/classification/04' },
                  { text: '05 Radiation Therapy Equipment', link: '/en/nmpa/classification/05' },
                  { text: '06 Medical Imaging Equipment', link: '/en/nmpa/classification/06' },
                  { text: '07 Diagnostic & Monitoring Instruments', link: '/en/nmpa/classification/07' },
                  { text: '08 Respiratory, Anesthesia & Emergency', link: '/en/nmpa/classification/08' },
                  { text: '09 Physical Therapy Equipment', link: '/en/nmpa/classification/09' },
                  { text: '10 Transfusion, Dialysis & Extracorporeal', link: '/en/nmpa/classification/10' },
                  { text: '11 Sterilization & Disinfection Equipment', link: '/en/nmpa/classification/11' },
                  { text: '12 Active Implantable Devices', link: '/en/nmpa/classification/12' },
                  { text: '13 Passive Implantable Devices', link: '/en/nmpa/classification/13' },
                  { text: '14 Infusion, Nursing & Protective Equipment', link: '/en/nmpa/classification/14' },
                  { text: '15 Patient Transfer Equipment', link: '/en/nmpa/classification/15' },
                  { text: '16 Ophthalmic Devices', link: '/en/nmpa/classification/16' },
                  { text: '17 Dental Devices', link: '/en/nmpa/classification/17' },
                  { text: '18 OB/GYN & Contraceptive Devices', link: '/en/nmpa/classification/18' },
                  { text: '19 Medical Rehabilitation Devices', link: '/en/nmpa/classification/19' },
                  { text: '20 Traditional Chinese Medicine Devices', link: '/en/nmpa/classification/20' },
                  { text: '21 Medical Software', link: '/en/nmpa/classification/21' },
                  { text: '22 Clinical Laboratory Instruments', link: '/en/nmpa/classification/22' },
                ],
              },
            ],
            '/en/shared/': [
              { text: 'International Standards', link: '/en/shared/standards' },
              {
                text: 'IMDRF Technical Documents', link: '/en/shared/imdrf',
                collapsed: true,
                items: [
                  { text: 'SaMD', link: '/en/shared/imdrf/samd' },
                  { text: 'AI/ML', link: '/en/shared/imdrf/aiml' },
                  { text: 'Cybersecurity', link: '/en/shared/imdrf/cyber' },
                  { text: 'UDI', link: '/en/shared/imdrf/udi' },
                  { text: 'MDSAP', link: '/en/shared/imdrf/mdsap' },
                  { text: 'GRRP', link: '/en/shared/imdrf/grrp' },
                  { text: 'Clinical Evidence', link: '/en/shared/imdrf/clinical' },
                  { text: 'Adverse Events', link: '/en/shared/imdrf/ae' },
                  { text: 'Regulatory Submission', link: '/en/shared/imdrf/rps' },
                  { text: 'Personalized Devices', link: '/en/shared/imdrf/pmd' },
                  { text: 'IVD', link: '/en/shared/imdrf/ivd' },
                  { text: 'Standards', link: '/en/shared/imdrf/standards' },
                ],
              },
            ],
            '/en/hub/': [
              { text: 'Reguverse Hub', link: '/en/hub/' },
            ],
            '/en/learn/': [
              { text: 'Reguverse Learn', link: '/en/learn/' },
            ],
            '/en/news/': [
              { text: 'Regulatory News', link: '/en/news/' },
              { text: 'EU MDR', link: '/en/news/eu_mdr' },
              { text: 'FDA', link: '/en/news/fda' },
              { text: 'NMPA', link: '/en/news/nmpa' },
              { text: 'UK MHRA', link: '/en/news/uk_mhra' },
              { text: 'Health Canada', link: '/en/news/canada' },
              { text: 'Australia TGA', link: '/en/news/australia_tga' },
              { text: 'Japan PMDA', link: '/en/news/japan_pmda' },
              { text: 'Korea MFDS', link: '/en/news/korea_mfds' },
              { text: 'Swissmedic', link: '/en/news/switzerland' },
              { text: 'Brazil ANVISA', link: '/en/news/brazil_anvisa' },
              { text: 'Saudi SFDA', link: '/en/news/saudi_sfda' },
              { text: 'Singapore HSA', link: '/en/news/singapore_hsa' },
              { text: 'India CDSCO', link: '/en/news/india_cdsco' },
              { text: 'Mexico COFEPRIS', link: '/en/news/mexico_cofepris' },
              { text: 'Argentina ANMAT', link: '/en/news/argentina_anmat' },
              { text: 'Taiwan TFDA', link: '/en/news/taiwan_tfda' },
              { text: 'New Zealand Medsafe', link: '/en/news/newzealand_medsafe' },
              { text: 'Indonesia BPOM', link: '/en/news/indonesia_bpom' },
              { text: 'Malaysia MDA', link: '/en/news/malaysia_mda' },
              { text: 'Thailand FDA', link: '/en/news/thailand_fda' },
              { text: 'Israel MOH', link: '/en/news/israel_moh' },
              { text: 'Hong Kong MDCO', link: '/en/news/hongkong_mdco' },
            ],
          },
          dynamicSidebarEn,
        ),
        socialLinks: [
          { icon: 'github', link: 'https://github.com/qian-qiang' }
        ],
        footer: {
          message: 'Content licensed under CC BY 4.0',
          copyright: 'Copyright © 2026 RASAAS'
        },
      }
    },
    zh: {
      label: '中文',
      lang: 'zh-CN',
      link: '/zh/',
      themeConfig: {
        nav: [
          { text: '首页', link: '/zh/' },
          {
            text: 'EU',
            items: [
              { text: 'EU MDR', link: '/zh/eu_mdr/' },
              { text: 'EU IVDR', link: '/zh/eu_ivdr/' },
            ],
          },
          { text: 'FDA', link: '/zh/fda/' },
          { text: 'NMPA', link: '/zh/nmpa/' },
          {
            text: '更多',
            items: [
              { text: '体系', link: '/zh/shared/standards' },
              { text: '法规速递', link: '/zh/news/' },
              { text: '法规解读', link: '/zh/insights/' },
              //{ text: 'Hub', link: '/zh/hub/' },
              //{ text: 'Learn', link: '/zh/learn/' },
              //{ text: '快速开始', link: '/zh/get-started' },
              //{ text: '联系我们', link: '/zh/contact' },
            ],
          },
        ],
        sidebar: zhSidebar,
        socialLinks: [
          { icon: 'github', link: 'https://github.com/qian-qiang' }
        ],
        footer: {
          message: '内容以 CC BY 4.0 许可证授权',
          copyright: 'Copyright © 2026 RASAAS'
        },
      }
    }
  },

  themeConfig: {
    logo: { light: '/logo.png', dark: '/logo-dark.png', alt: 'DocMCP' },
    search: {
      provider: 'local',
      options: {
        locales: {
          zh: {
            translations: {
              button: {
                buttonText: '搜索文档',
                buttonAriaLabel: '搜索文档'
              },
              modal: {
                displayDetails: '显示详细列表',
                resetButtonTitle: '清除查询',
                backButtonTitle: '关闭搜索',
                noResultsText: '无法找到相关结果',
                footer: {
                  selectText: '选择',
                  navigateText: '切换',
                  closeText: '关闭'
                }
              }
            }
          }
        },
        _render(src, env, md) {
          const path = env.relativePath || ''
          const isFulltextPage = /(?:nmpa|fda|shared)\/guidance\//.test(path) &&
            !path.endsWith('guidance.md')
          if (isFulltextPage) {
            const title = env.frontmatter?.title || ''
            const desc = env.frontmatter?.description || ''
            return md.render(`# ${title}\n\n${desc}`)
          }
          return md.render(src, env)
        },
        miniSearch: {
          options: {
            tokenize(text: string) {
              const segmenter = (Intl as any).Segmenter
                ? new (Intl as any).Segmenter('zh-CN', { granularity: 'word' })
                : null
              if (segmenter) {
                const segments: string[] = []
                for (const seg of segmenter.segment(text)) {
                  if (seg.isWordLike) segments.push(seg.segment)
                }
                if (segments.length > 0) return segments
              }
              return text.split(/[\s\p{P}]+/u).filter(Boolean)
            }
          },
          searchOptions: {
            fuzzy: 0.2,
            prefix: true,
            boost: { title: 4, text: 2, titles: 1 }
          }
        }
      }
    }
  }
})
