#!/usr/bin/env python3
"""
Regenerate the EU MDR other-standards INDEX pages (docs/{zh,en}/eu_mdr/other-standards.md)
from eu_mdr/other_standards/standards-*.json data.

The per-category sub-pages are generated by regen_other_standards_md.py; this script
keeps the index page (total count + category table) consistent with the data layer.
"""

import json
from pathlib import Path

from regen_other_standards_md import CATEGORY_LABELS, json_key_to_md_slug

REPO = Path(__file__).resolve().parent.parent
JSON_DIR = REPO / "eu_mdr" / "other_standards"

EN_PAGE = REPO / "docs" / "en" / "eu_mdr" / "other-standards.md"
ZH_PAGE = REPO / "docs" / "zh" / "eu_mdr" / "other-standards.md"

EN_HEADER = """---
title: Other Applicable Standards
---

# Other Applicable Standards (Non-Harmonised)

Beyond harmonised standards, medical device manufacturers commonly apply the following international standards (ISO, IEC, ASTM, etc.) to demonstrate compliance with EU MDR GSPR. While these do not create a *presumption of conformity*, they represent accepted state-of-the-art practices.

::: info Total: **{total}** standards across **{cats}** categories
:::

## Categories

| Category | Standards | Key Standards |
|----------|-----------|---------------|
"""

EN_FOOTER = """
---

::: tip Navigation
Click on a category above to see all standards in that category with their scope, applicable GSPRs, and official source links.
:::
"""

ZH_HEADER = """---
title: 其他适用标准
---

# 其他适用标准（非协调标准）

除协调标准外，医疗器械制造商通常还应用以下国际标准（ISO、IEC、ASTM 等）来证明符合 EU MDR GSPR 要求。虽然这些标准不产生*符合性推定*，但它们代表了公认的技术水平。

::: info 共 **{total}** 条标准，分布于 **{cats}** 个类别
:::

## 标准分类

| 类别 | 标准数量 | 代表性标准 |
|------|----------|------------|
"""

ZH_FOOTER = """
---

::: tip 导航
点击上方类别可查看该类别下的所有标准，包括标准范围、适用 GSPR 条款和官方来源链接。
:::
"""


def key_standards(standards: list, limit: int = 3) -> str:
    numbers = [s.get("number", "") for s in standards if s.get("number")]
    shown = ", ".join(numbers[:limit])
    if len(numbers) > limit:
        shown += "..."
    return shown


def main():
    rows = []
    total = 0
    for jf in sorted(JSON_DIR.glob("standards-*.json")):
        category_key = jf.stem.replace("standards-", "")
        data = json.loads(jf.read_text(encoding="utf-8"))
        standards = data.get("standards", [])
        total += len(standards)
        labels = CATEGORY_LABELS.get(category_key, {})
        rows.append({
            "slug": json_key_to_md_slug(category_key),
            "en": labels.get("en", category_key),
            "zh": labels.get("zh", category_key),
            "count": len(standards),
            "key": key_standards(standards),
        })

    cats = len(rows)

    en_rows = sorted(rows, key=lambda r: r["en"].lower())
    en_lines = [
        f"| [{r['en']}](./other-standards/{r['slug']}) | {r['count']} | {r['key']} |"
        for r in en_rows
    ]
    EN_PAGE.write_text(
        EN_HEADER.format(total=total, cats=cats) + "\n".join(en_lines) + EN_FOOTER,
        encoding="utf-8",
    )

    zh_lines = [
        f"| [{r['zh']}](./other-standards/{r['slug']}) | {r['count']} | {r['key']} |"
        for r in en_rows
    ]
    ZH_PAGE.write_text(
        ZH_HEADER.format(total=total, cats=cats) + "\n".join(zh_lines) + ZH_FOOTER,
        encoding="utf-8",
    )

    print(f"Regenerated index pages: {cats} categories, {total} standards.")


if __name__ == "__main__":
    main()
